# Site settings
title: Super Mario Bean
email: david.fu.zju.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A reader lives a thousand lives before he dies, the man who never reads lives only one.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://supermariobean.github.io" # the base hostname & protocol for your site
github_username:  supermariobean
resume: supermariobean
resume_name: David Fu

# Build settings
markdown: kramdown

# Comments settings
comments: 
  provider: duoshuo
  duoshuo:
    short_name: supermariobean
